excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - "*.generated.swift"
  - "*Utiles.swift"
  - "*/Models/Realm.swift"
  - "*/Helpers/Utilities/RealmUtiles.swift"

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - force_try
  - identifier_name
  - function_body_length
  - cyclomatic_complexity
  - line_length
  - large_tuple